### ISSUE TITLE
Proposal: Modify options Behavior in FileReaderBuilder for Option Merging

### ISSUE THREAD

**Issue by paulsasi** [damavis/damavis-spark#16]
**Issue Description:**

In the FileReaderBuilder class under the com.damavis.spark.resource.file package, I've observed that the option and options functions behave differently, which may lead to varying interpretations by users.

option: Adds an option to the existing set of options.
options: Overwrites the existing options with the provided options map.

**Expected Behavior**

I propose that the options function should merge the provided options with the existing options using a strategy that allows users to add or update options without completely overwriting them. This would make the behavior of options more consistent with the behavior of option.

This change might also necessitate corresponding updates in the FileWriterBuilder class for consistency.

**Example**

For instance, consider the following code snippet:

```
FileReaderBuilder(format, path)
      .options(
        Map(
          "inferSchema" -> inferSchema.toString,
          "header" -> header.toString,
          "delimiter" -> delimiter
        ))
      .options(options)
```

In this example, it could be beneficial for users if the second options call merged the provided options with the ones set in the first options call, rather than entirely overwriting them.

**Comment by piffall** [comment]
Hi @paulsasi , I'm completely agree. Consistency is so important. Would you like to implement this change and open a PR?

**Comment by paulsasi** [comment]
Sure! I'll work on it as soon as possible.
